apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: minha-app
  namespace: producao
spec:
  replicas: 10
  selector:
    matchLabels:
      app: minha-app
  template:
    metadata:
      labels:
        app: minha-app
    spec:
      containers:
        - name: minha-app
          image: jonesprado/rollback-deployment:v2
          ports:
            - containerPort: 80
          env:
            - name: VERSAO_TESTE
              value: "2"
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 75
        - pause: {}